Add files enrichment using VT data
googleinterns/step242-2020 pull request #48
Opened 2020-09-01 14:10 UTC by niedziol

Closes #47

2020-09-02 08:48 UTC, mgmacias95 commented on capstone/files/enrichment/virustotal.py
> +    print("No module 'vt' found. Install pip install vt-py")
You can check the module's name in the exception object:

```python
>>> try:
...     import blablabla
... except ImportError as e:
...     print(e.name)
... 
blablabla
```

So you can refactor all imports in a single try-except block

2020-09-02 08:51 UTC, mgmacias95 commented on capstone/files/enrichment/virustotal.py
> +def debug(msg):
This logger is very basic, this is a good chance to learn about real python loggers. You'd need to configure two logger handlers:
* A [`BaseRotating`](https://docs.python.org/3/library/logging.handlers.html#baserotatinghandler) one.
* A [`Stream`](https://docs.python.org/3/library/logging.handlers.html#streamhandler) which will only be enabled if the `DEBUG` flag is set.

2020-09-02 08:52 UTC, mgmacias95 commented on capstone/files/enrichment/virustotal.py
> +def in_database(data, hash):
Is this used?

2020-09-08 17:11 UTC, niedziol commented
One TODO is left. We need to decide when the file is marked as `malicious`.

2020-09-09 07:38 UTC, karpp requested changes

2020-09-09 07:38 UTC, karpp commented on capstone/files/enrichment/virustotal.py
> +    logging.info(alert_file_location)
Same, do you need it in logs?

2020-09-09 07:38 UTC, karpp commented on capstone/files/enrichment/virustotal.py
> +    if msg:
Log error on else

2020-09-09 07:38 UTC, karpp commented on capstone/files/enrichment/virustotal.py
> +        exit(0)
It's not obvious that `get_file_info` can exit program on fail. Mark it on docstring or change to raise/return None

2020-09-09 09:07 UTC, karpp submitted a review, later dismissed
LGTM

2020-09-10 09:26 UTC, karpp approved these changes
LGTM

2020-09-17 11:01 UTC, mgmacias95 reviewed
update wazuh rules

2020-09-18 14:46 UTC, mgmacias95 approved these changes

2020-09-18 16:21 UTC, merged