Network enrichment script
googleinterns/step242-2020 pull request #49
Opened 2020-09-07 08:26 UTC by karpp

2020-09-07 08:26 UTC, karpp commented
Deployment script is not ready

2020-09-08 09:07 UTC, niedziol requested changes

2020-09-08 09:52 UTC, mgmacias95 requested changes

2020-09-08 09:52 UTC, mgmacias95 commented on capstone/network-enrichment/custom_vt_network.py
> +        logging.error('Request to elasticsearch failed')
Add response text from elastic search

2020-09-08 09:52 UTC, mgmacias95 commented on capstone/network-enrichment/custom_vt_network.py
> +        logging.info('IP found again: ' + alert_json['data']['srcip'])
f-string

2020-09-08 09:52 UTC, mgmacias95 commented on capstone/network-enrichment/custom_vt_network.py
> +import time
is this used?

2020-09-08 16:56 UTC, niedziol requested changes

2020-09-08 16:56 UTC, niedziol commented on capstone/network-enrichment/deploy.sh
> +    if [[ "$OSSECCONF" != *"custom-vt-network"* ]]; then
This is not working, you have multiple copy of the same config in `ossec.conf`.

2020-09-09 13:25 UTC, niedziol approved these changes
LGTM

2020-09-09 16:54 UTC, merged